// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonaBlog.Models;

namespace PersonaBlog.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("PersonaBlog.Models.AcceptedRequests", b =>
                {
                    b.Property<Guid>("AcceptedId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Priority");

                    b.Property<Guid?>("RequestId");

                    b.HasKey("AcceptedId");

                    b.HasIndex("RequestId");

                    b.ToTable("AcceptedRequests");
                });

            modelBuilder.Entity("PersonaBlog.Models.RequestsModel", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AcceptRequest");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Subject")
                        .IsRequired();

                    b.HasKey("RequestId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("PersonaBlog.Models.AcceptedRequests", b =>
                {
                    b.HasOne("PersonaBlog.Models.RequestsModel", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId");
                });
#pragma warning restore 612, 618
        }
    }
}
